// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzyA4x3rihzcmZP6Bro-Ms66Q7UVcBk9Q',
    appId: '1:627540500366:web:6c5cd52fa628a686204edf',
    messagingSenderId: '627540500366',
    projectId: 'alvas-managment',
    authDomain: 'alvas-managment.firebaseapp.com',
    storageBucket: 'alvas-managment.appspot.com',
    measurementId: 'G-ZQWPTF4308',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfO3jnvIs3D6TZsElnNI4mKnXHEXm99Uk',
    appId: '1:627540500366:android:79402be82d08ab45204edf',
    messagingSenderId: '627540500366',
    projectId: 'alvas-managment',
    storageBucket: 'alvas-managment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFxktkwHQQa3ENTIxz8STUGDS15PO3piM',
    appId: '1:627540500366:ios:2e5583c2bdc175ee204edf',
    messagingSenderId: '627540500366',
    projectId: 'alvas-managment',
    storageBucket: 'alvas-managment.appspot.com',
    iosBundleId: 'com.example.alvasMangment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFxktkwHQQa3ENTIxz8STUGDS15PO3piM',
    appId: '1:627540500366:ios:2e5583c2bdc175ee204edf',
    messagingSenderId: '627540500366',
    projectId: 'alvas-managment',
    storageBucket: 'alvas-managment.appspot.com',
    iosBundleId: 'com.example.alvasMangment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzyA4x3rihzcmZP6Bro-Ms66Q7UVcBk9Q',
    appId: '1:627540500366:web:7d80ae551416df8f204edf',
    messagingSenderId: '627540500366',
    projectId: 'alvas-managment',
    authDomain: 'alvas-managment.firebaseapp.com',
    storageBucket: 'alvas-managment.appspot.com',
    measurementId: 'G-YCVGK5HMHW',
  );
}
